[project]
name = "assistant-redux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "facenet-pytorch>=2.5.3",
    "mediapipe>=1.0.1",
    "numpy>=2.5.2",
    "openai-agents>=0.22.0",
    "openai-whisper>=20250625",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pydantic-numpy>=8.0.1",
    "samplerate>=0.2.4",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
]
